version: "3.8"

services:
  db:
    image: "postgres:1.0.0"
    restart: always
    container_name: "doc-pgsql-container"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  backend:
    image: 'backend:1.0.0'
    build:
      context: ./container_name
      dockerfile: 'devops-demo-container'
    ports:
      - "8989:8989"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: 'frontend:1.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - backend