# Use a base image with Java and Maven installed
# FROM maven:3.8.4-openjdk-17 AS build


FROM openjdk:17-jdk-alpine
COPY target/*.jar app.jar
EXPOSE 8989
ENTRYPOINT ["java","-jar","app.jar"]
# Set the working directory in the container
# WORKDIR /app

# # Copy the Maven project file and the source code
# COPY pom.xml .
# COPY src ./src

# # Download dependencies and build the application
# RUN mvn clean package -DskipTests

# # Create a new stage based on OpenJDK image
# FROM openjdk:17-slim

# # Set the working directory in the container
# WORKDIR /app

# # Copy the JAR file from the previous stage
# COPY --from=build /app/target/*.jar app.jar

# # Expose the port the application runs on
# EXPOSE 8989

# # Command to run the application
# CMD ["java", "-jar", "app.jar"]
